Repository newrelic/node-test-utilities, pull requests merged in 2020-07, with the labels that each got.

#45 GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/enhancement-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#47 Added copyright headers to source files
  bin/publish-docs.sh
  bin/version-manager.js
  index.js
  lib/agent.js
  lib/assert.js
  lib/util.js
  lib/versioned/matrix.js
  lib/versioned/packager.js
  lib/versioned/printers/index.js
  lib/versioned/printers/pretty.js
  lib/versioned/printers/printer.js
  lib/versioned/printers/simple.js
  lib/versioned/runner.js
  lib/versioned/suite.js
  lib/versioned/test.js
  tests/unit/agent.tap.js
  tests/unit/assert.tap.js
  tests/unit/index.tap.js
  tests/unit/newrelic.js
  tests/unit/util.tap.js
  tests/unit/versioned/matrix.tap.js
  tests/unit/versioned/mock-tests/other.mock.js
  tests/unit/versioned/mock-tests/redis.mock.js
  tests/unit/versioned/suite.tap.js
  tests/unit/versioned/test.tap.js
Labels: ready-for-review

#46 Added Apache 2.0 license
  LICENSE
Labels: ready-for-review

#48 Added code of conduct file
  CODE_OF_CONDUCT.md
Labels: ready-for-review

#49 Added contributing guidelines files
  CONTRIBUTING.md
Labels: ready-for-review

#50 Third party notices
  .gitignore
  THIRD_PARTY_NOTICES.md
  lib/assert.js
  package.json
  third_party_manifest.json
Labels: ready-for-review

#52 Updated README
  README.md
Labels: ready-for-review

#59 Tightens Up "Already Declared in Upper Scope" Lint Warnings
  lib/versioned/runner.js
  lib/versioned/suite.js
Labels: risk:low, semver:patch

#60 Release v4.0.0
  CHANGELOG.md
  CONTRIBUTING.md
Labels: risk:low, semver:major
